# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EwFsRcEn4_cuTDD3JqvZUCMqxNwAx8HM
"""


!pip install -U -q pyTelegramBotAPI google-genai

import telebot
import traceback
from google import genai

TOKEN_TELEGRAM = "7750393898:AAGJqgXN8R15kdwSnWfrA1VUWPLQadMLbZQ"
CLAVE_GEMINI = "AIzaSyBz9YNcaPwjpTUGGRSIvOUL0D3OA_KPwe8"

bot = telebot.TeleBot(TOKEN_TELEGRAM)
client = genai.Client(api_key=CLAVE_GEMINI)

MODELO_GEMINI = "gemini-2.5-flash"

print("Claves configuradas correctamente")

from google.colab import files

print("Sube el archivo ley_limpia.txt")
uploaded = files.upload()

NOMBRE_ARCHIVO = list(uploaded.keys())[0]
print("Archivo cargado:", NOMBRE_ARCHIVO)

with open(NOMBRE_ARCHIVO, "r", encoding="utf-8") as f:
    texto_limpio = f.read()

print("Texto cargado correctamente")
print("Caracteres cargados:", len(texto_limpio))

print(texto_limpio[:500])

@bot.message_handler(commands=["start"])
def start(message):
    bot.reply_to(
        message,
        "¡Qué tal! Soy tu asistente virtual, te apoyo con gusto para consultar la Ley de Educación de Nuevo León.\n\n"
        "Puedes preguntarme por artículos, conceptos o implicaciones para escuelas, docentes, directivos, supervisores e inspectores.\n\n"
        "Desarrollado por Maricruz Acevedo Menchaca."
    )


@bot.message_handler(func=lambda message: True)
def responder(message):
    try:
        pregunta = message.text

        prompt = f"""
Eres un asistente técnico del Estado de Nuevo León.

Tu función es responder preguntas sobre la Ley de Educación de Nuevo León, usando el texto base proporcionado.

Instrucciones:
- Responde de forma clara, ordenada y útil.
- Usa lenguaje comprensible para docentes, directivos, supervisores e inspectores.
- Si encuentras artículos relacionados, menciónalos.
- No inventes artículos.
- Si no estás seguro, dilo.
- Si el texto no contiene la respuesta, dilo claramente.
- Cuando sea útil, responde con viñetas.
- Si la pregunta pide interpretación, explica la implicación práctica en contexto escolar.
- Mantén tono institucional, cercano y respetuoso.

Texto base:
{texto_limpio[:120000]}

Pregunta:
{pregunta}
"""

        respuesta = client.models.generate_content(
            model=MODELO_GEMINI,
            contents=prompt
        )

        texto_respuesta = respuesta.text if respuesta.text else "No pude generar respuesta."
        bot.reply_to(message, texto_respuesta[:4000])

    except Exception as e:
        print("ERROR REAL:")
        print(traceback.format_exc())
        bot.reply_to(message, f"Hubo un error: {e}")


print("🚀 Bot activo. Ve a Telegram y escribe /start")
bot.infinity_polling()
